name: Format code

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    concurrency: edit-repo

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install .Net tools
        run: dotnet tool restore

      - name: Run fantomas
        run: dotnet fantomas .

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python tools
        run: pip install -r requirements.txt

      - name: Run ruff
        run: ruff check --exit-zero --fix --extend-select I && ruff format

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Run gofmt
        run: gofmt -s -w .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Format code"
