name: Generate readmes

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  readme:
    name: Generate readmes
    runs-on: ubuntu-latest
    concurrency: edit-repo

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'tools/go.mod'

      - name: Generate readmes
        run: go run . readmes
        working-directory: tools

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Generate readmes"
