name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'tools/go.mod'

      - name: Decrypt test data
        run: go run . tests decrypt
        working-directory: tools
        env:
          AOC_SECRET_KEY: ${{ secrets.AOC_SECRET_KEY }}

      - name: Run tests
        run: go run . tests run
        working-directory: tools
